#!/bin/bash

###################################################################
#Script Name	: Configure Unique Hostnames
#Description	: Generate unique hostnames for nonpersistent desktops
#Args           :
#Author       	: TJ Norred
#Email         	: tjnorred@gmail.com
###################################################################


# Generate the random word from /dict/words
get_word () { 
	echo `shuf -n1 /usr/share/dict/words` 
}

# Generate the hostname
get_hostname () {
	host=$(get_word)
	domain=$(get_word)
	hostname="$host.$domain.com"
	echo "The newly selected hostname is $hostname . . . "
}

get_hostname

# Create a new hostname file
echo $hostname > /etc/hostname
