# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "private_network", ip: "X.X.X.X"
  config.vm.synced_folder "../local/data", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
	vb.name = "VM_Name"
	vb.cpus = 2
	vb.memory = 1024

   end

   config.vm.provision "shell", inline: <<-SHELL
     apt update
     apt install -y apache2
	   apt install -y php
	   apt install -y mysql-server
	   apt install -y php7.*-mysql
   SHELL
end
